//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_04___Variadas_Tipadas_Implicitamente___Var
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loja
    {
        public string LO_Loja { get; set; }
        public short LO_Empresa { get; set; }
        public string LO_Endereco { get; set; }
        public Nullable<decimal> LO_Numero { get; set; }
        public string LO_Bairro { get; set; }
        public string LO_Municipio { get; set; }
        public string LO_UF { get; set; }
        public string LO_Cep { get; set; }
        public string LO_CGC { get; set; }
        public string LO_InscricaoEstadual { get; set; }
        public string LO_Telefone { get; set; }
        public string LO_Fax { get; set; }
        public string LO_Localizacao { get; set; }
        public string LO_Registro { get; set; }
        public System.DateTime LO_UltimaConexao { get; set; }
        public string LO_SituacaoConexao { get; set; }
        public string LO_TelComunicacao { get; set; }
        public System.DateTime LO_UltimoProcesso { get; set; }
        public string LO_ArquivosProcessar { get; set; }
        public string LO_SituacaoProcesso { get; set; }
        public string LO_SituacaoCaixa { get; set; }
        public string LO_Situacao { get; set; }
        public string LO_Gerente { get; set; }
        public string LO_CriaArquivos { get; set; }
        public Nullable<System.DateTime> LO_ProximoInventario { get; set; }
        public Nullable<System.DateTime> LO_UltimoInventario { get; set; }
        public string LO_Razao { get; set; }
        public string LO_NomeLogotipo { get; set; }
        public Nullable<int> LO_OrdemLoja { get; set; }
        public Nullable<int> LO_PosicaoLoja { get; set; }
        public Nullable<int> LO_Regiao { get; set; }
        public string LO_SituacaoEnvio { get; set; }
        public string LO_ProcessaNota { get; set; }
        public string LO_ComprasOnLine { get; set; }
        public string LO_ProcessaAuditorEstoque { get; set; }
        public string LO_ProcessaEstoque { get; set; }
        public string LO_MostraEstoque { get; set; }
        public Nullable<System.DateTime> LO_PerInvInicial { get; set; }
        public Nullable<System.DateTime> LO_PerInvFinal { get; set; }
        public string LO_IpLoja { get; set; }
        public string LO_NomeServidor { get; set; }
        public Nullable<int> LO_BancoOnLine { get; set; }
        public string LO_LinkedServer { get; set; }
        public string LO_OrdemLojaMU { get; set; }
        public string LO_CriaEstoque { get; set; }
        public Nullable<int> LO_NroFuncionario { get; set; }
        public Nullable<double> LO_MetragemLoja { get; set; }
        public Nullable<decimal> LO_CodigoUF { get; set; }
        public Nullable<decimal> LO_CodigoMunicipio { get; set; }
        public string LO_NomeFantasia { get; set; }
        public string LO_CodigoPais { get; set; }
        public string LO_EnderecoNFe { get; set; }
        public Nullable<int> LO_EnderecoNroNFe { get; set; }
        public string LO_ComplementoNFe { get; set; }
        public Nullable<int> LO_OrdemDistribuicao { get; set; }
        public string LO_EmaiLoja { get; set; }
        public string LO_EnviaProdutoLoja { get; set; }
        public string LO_Conexao { get; set; }
        public string LO_GrupoRegiao { get; set; }
        public Nullable<int> LO_NroVendedor { get; set; }
        public string LO_LogoPedido { get; set; }
        public string LO_InscricaoMunicipal { get; set; }
        public string LO_DDD { get; set; }
        public string LO_TipoTransferencia { get; set; }
        public string LO_DMAC { get; set; }
        public string Lo_site { get; set; }
        public string Lo_Televendas { get; set; }
        public string lo_nomeLoja { get; set; }
        public string lo_emailnfe { get; set; }
        public Nullable<int> lO_Contigencia { get; set; }
    }
}
